### ISSUE TITLE
Doesn't build on zig 0.13?

### ISSUE THREAD

**Issue by VorpalBlade** [andrewrk/poop#55]
I'm a rust / C++ developer (that want to use the performance counter stuff), so I may not just know what I'm doing:

```console
❯ zig build
install
└─ install poop
   └─ zig build-exe poop Debug native 1 errors
src/main.zig:379:57: error: no field named 'struct' in union 'builtin.Type'
            inline for (@typeInfo(Command.Measurements).@"struct".fields) |field| {
                                                        ^~~~~~~~~
/usr/lib/zig/std/builtin.zig:256:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
referenced by:
    callMain: /usr/lib/zig/std/start.zig:524:32
    callMainWithArgs: /usr/lib/zig/std/start.zig:482:12
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
error: the following command failed with 1 compilation errors:
/usr/bin/zig build-exe -ODebug -Mroot=/home/arvid/src/poop/src/main.zig --cache-dir /home/arvid/src/poop/.zig-cache --global-cache-dir /home/arvid/.cache/zig --name poop --listen=- 
Build Summary: 0/3 steps succeeded; 1 failed (disable with --summary none)
install transitive failure
└─ install poop transitive failure
   └─ zig build-exe poop Debug native 1 errors
error: the following build command failed with exit code 1:
/home/arvid/src/poop/.zig-cache/o/ecfa02dd1bc8f1b648892a6b82714a07/build /usr/bin/zig /home/arvid/src/poop /home/arvid/src/poop/.zig-cache /home/arvid/.cache/zig --seed 0x8984926f -Zaf44668180b4f648
❯ git describe --tags
0.4.0-15-g13c930a
❯ zig version
0.13.0
```

* Zig 0.13.0 was installed from Arch Linux package
* I get the same error if I check out the latest release tag 0.4.0

Is there anything like `cargo install` for Zig that I could use instead? Any sort of `zigup` to get the right version?

**Comment by andrewrk** [comment]
I created the zig-0.13.0 branch which builds with zig 0.13.0 and tagged release 0.5.0. Hope that helps!
