### ISSUE TITLE
zig won't build in 0.15.1

### ISSUE THREAD

**Issue by havok4u** [andrewrk/poop#80]
I have the same issue as Issue #76 with 0.14.1 through 0.15.0 
```
$ zig build
install
└─ install poop
   └─ zig build-exe poop Debug native 1 errors
src/main.zig:88:36: error: root source file struct 'fs.File' has no member named 'stdout'
    var stdout_writer = std.fs.File.stdout().writer(&stdout_buffer);
                        ~~~~~~~~~~~^~~~~~~
/home/tepkes/Development/Zig/zig-x86_64-linux-0.15.0-dev.643+dc6ffc28b/lib/std/fs/File.zig:1:1: note: struct declared here
/// The OS-specific file descriptor or file handle.
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    callMain [inlined]: /home/tepkes/Development/Zig/zig-x86_64-linux-0.15.0-dev.643+dc6ffc28b/lib/std/start.zig:675:37
    callMainWithArgs [inlined]: /home/tepkes/Development/Zig/zig-x86_64-linux-0.15.0-dev.643+dc6ffc28b/lib/std/start.zig:635:20
    posixCallMainAndExit: /home/tepkes/Development/Zig/zig-x86_64-linux-0.15.0-dev.643+dc6ffc28b/lib/std/start.zig:590:36
    2 reference(s) hidden; use '-freference-trace=5' to see all references
error: the following command failed with 1 compilation errors:
```

**but in 0.15.1 the problem changes,**
```
$ zig build
install
└─ install poop
   └─ compile exe poop Debug native 1 errors
src/main.zig:91:42: error: struct 'array_list.Aligned(main.Command,null)' has no member named 'init'
    var commands = std.ArrayList(Command).init(arena);
                   ~~~~~~~~~~~~~~~~~~~~~~^~~~~
/home/linuxbrew/.linuxbrew/Cellar/zig/0.15.1/lib/zig/std/array_list.zig:606:12: note: struct declared here
    return struct {
           ^~~~~~
referenced by:
    callMain [inlined]: /home/linuxbrew/.linuxbrew/Cellar/zig/0.15.1/lib/zig/std/start.zig:627:37
    callMainWithArgs [inlined]: /home/linuxbrew/.linuxbrew/Cellar/zig/0.15.1/lib/zig/std/start.zig:587:20
    posixCallMainAndExit: /home/linuxbrew/.linuxbrew/Cellar/zig/0.15.1/lib/zig/std/start.zig:542:36
    2 reference(s) hidden; use '-freference-trace=5' to see all references
error: the following command failed with 1 compilation errors:
```
This looks like a great tool and I really want to try to use it. Thanks

**Comment by nunokaeru** [comment]
Build from this fork / branch for now https://github.com/andrewrk/poop/pull/77

**Comment by rtfb** [comment]
#77 is now landed. I've built successfully with zig 0.15.2 yesterday. Good to close?
