### ISSUE TITLE
Doesn't build with Zig 0.14.1

### ISSUE THREAD

**Issue by VorpalBlade** [andrewrk/poop#76]
Similar to #55, I cannot find a version that will build with zig 0.14.1 (the version packaged by Arch Linux).

0.5.0 and the zig-0.13.0 branches fail with:

```console
❯ git checkout zig-0.13.0 
branch 'zig-0.13.0' set up to track 'origin/zig-0.13.0'.
Switched to a new branch 'zig-0.13.0'
❯ zig build
install
└─ install poop
   └─ zig build-exe poop Debug native 1 errors
src/main.zig:379:57: error: no field named 'Struct' in union 'builtin.Type'
            inline for (@typeInfo(Command.Measurements).Struct.fields) |field| {
                                                        ^~~~~~
/usr/lib/zig/std/builtin.zig:568:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
referenced by:
    posixCallMainAndExit: /usr/lib/zig/std/start.zig:660:37
    _start: /usr/lib/zig/std/start.zig:468:40
    3 reference(s) hidden; use '-freference-trace=5' to see all references
error: the following command failed with 1 compilation errors:
/usr/bin/zig build-exe -ODebug -Mroot=/home/arvid/src/profiling/poop/src/main.zig --cache-dir /home/arvid/src/profiling/poop/.zig-cache --global-cache-dir /home/arvid/.cache/zig --name poop --zig-lib-dir /usr/lib/zig/ --listen=- 
Build Summary: 0/3 steps succeeded; 1 failed
install transitive failure
└─ install poop transitive failure
   └─ zig build-exe poop Debug native 1 errors
error: the following build command failed with exit code 1:
/home/arvid/src/profiling/poop/.zig-cache/o/8084dba906fd17453b1e791c16dbafa9/build /usr/bin/zig /usr/lib/zig /home/arvid/src/profiling/poop /home/arvid/src/profiling/poop/.zig-cache /home/arvid/.cache/zig --seed 0x17709cca -Z0431a9e42a59e167
```

Main fails with:

```console
❯ zig build          
install
└─ install poop
   └─ zig build-exe poop Debug native 1 errors
src/main.zig:88:36: error: root source file struct 'fs.File' has no member named 'stdout'
    var stdout_writer = std.fs.File.stdout().writer(&stdout_buffer);
                        ~~~~~~~~~~~^~~~~~~
/usr/lib/zig/std/fs/File.zig:1:1: note: struct declared here
/// The OS-specific file descriptor or file handle.
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    posixCallMainAndExit: /usr/lib/zig/std/start.zig:660:37
    _start: /usr/lib/zig/std/start.zig:468:40
    3 reference(s) hidden; use '-freference-trace=5' to see all references
error: the following command failed with 1 compilation errors:
/usr/bin/zig build-exe -ODebug -Mroot=/home/arvid/src/profiling/poop/src/main.zig --cache-dir /home/arvid/src/profiling/poop/.zig-cache --global-cache-dir /home/arvid/.cache/zig --name poop --zig-lib-dir /usr/lib/zig/ --listen=- 
Build Summary: 0/3 steps succeeded; 1 failed
install transitive failure
└─ install poop transitive failure
   └─ zig build-exe poop Debug native 1 errors
error: the following build command failed with exit code 1:
/home/arvid/src/profiling/poop/.zig-cache/o/ad8530cffd8cbdac358d927edde69499/build /usr/bin/zig /usr/lib/zig /home/arvid/src/profiling/poop /home/arvid/src/profiling/poop/.zig-cache /home/arvid/.cache/zig --seed 0xedc03efc -Zf7558ef2085bad49
```

(Since zig has so many breaking changes, a zigup tool similar to rustup would be quite useful, and there could be a file in the project to identify what toolchain version is needed.)

**Comment by WGrav01** [comment]
You can use [anyzig](https://github.com/marler8997/anyzig) sort of like rustup
